### ISSUE TITLE
sudo removal not commited

### ISSUE THREAD

**Issue by rsyring** [level12/python-test-multi#10]
@guruofgentoo shouldn't there be commits in this repo for the removal of sudo and the other recent updates you did?

https://level12.slack.com/archives/C02DAPS3T/p1529689075000539

**Comment by guruofgentoo** [comment]
Quite right - but I don't have write access to this repository. I'll get that taken care of on Monday.

**Comment by n8harmon** [comment]
@guruofgentoo You should have write access now.
