### ISSUE TITLE
Do we still need pyodbc stuff?

### ISSUE THREAD

**Issue by rsyring** [level12/python-test-multi#13]
@guruofgentoo do we still need pyodbc stuff in these images?

https://github.com/level12/python-test-multi/blob/master/Dockerfile#L53

**Comment by guruofgentoo** [comment]
Not for any of our current projects, no.

**Comment by rsyring** [comment]
It's being used by some libraries.  See: https://github.com/level12/python-test-multi/pull/17#discussion_r1135896545
