### ISSUE TITLE
18.04 Image Broken

### ISSUE THREAD

**Issue by calebsyring** [level12/python-test-multi#20]
See the failed build: https://hub.docker.com/repository/registry-1.docker.io/level12/python-test-multi/builds/8577ba91-35ed-4f4b-a5ca-1c5635950c80

Looks like deadsnakes no longer supports Ubuntu 18. None of our apps seem to use it. Just drop the image?

**Comment by rsyring** [comment]
Yes, you can drop the image.

**Comment by calebsyring** [comment]
Dropped the branches and removed the tags from docker. Closing.
